apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jcb2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-jcb2@sha256:deb84314a2ef715499409bd366b6d281938c8c33dde842bc0a30ace15dafa8bc
        name: my-nodejs
        resources: {}
status: {}
